### ISSUE TITLE
Table to map IP with country

### ISSUE THREAD

**Issue by cheekujodhpur** [cheekujodhpur/ipho2015#1]
We need a mongodb collection which maps IP addresses of the machines with the respective countries along with the number of leaders corresponding to it. This will also allow us to show the required number of voting panels for the client machines. 

This will also affect users.sh. It is better to show the name of the country rather than the IP which is logged in

**Comment by sandeshkalantre** [comment]
Done with country_code_ip.txt and the initialize script.
