### ISSUE TITLE
unwanted keystroke

### ISSUE THREAD

**Issue by arijit-ind** [cheekujodhpur/ipho2015#2]
Measures to be taken (either block f5 ,backspace etc.) so that voting right is not affected from unwanted key stroke

may be done with polling coming in message box like window (where no tool/menu bar/keystroke will affect)

**Comment by arijit-ind** [comment]
_leaders can't download the file which has been uploaded by the convener
for them._

*whenever packed checkbox is checked Theory 1,Theory 2 and Theory 3 is
being renamed to Theory 1 *

**Comment by cheekujodhpur** [comment]
@sandeshkalantre Confirm removal of these bugs.

**Comment by cheekujodhpur** [comment]
@sandeshkalantre Confirm removal of these bugs, mentioned by arijit

**Comment by sandeshkalantre** [comment]
Confirmed.
